### ISSUE TITLE
LPhyStudio 1.2.0 error when loading script -- lphy.util.IOUtils class not found 

### ISSUE THREAD

**Issue by kche309** [bioDS/beast-phylonco#31]
Running LPhyStudio 1.2.0 from IntelliJ and trying to load a script produces a class not found error `Caused by: java.lang.ClassNotFoundException: lphy.util.IOUtils`.

LPhyStudio was run using two methods:
* using the `runLPhyStudio` gradle task
* as an application with main class `lphystudio.app.LinguaPhyloStudio`
When selecting a script from examples (File -> Examples) and loading a new script (File -> Open script) produces the `lphy.util.IOUtils` error message.

**Comment by walterxie** [comment]
It is caused by loading wrong version of lphy (1.3) if it exists in the Gradle local repo. I will investigate the Gradle functions in the build further: 

<img width="661" alt="Screen Shot 2022-08-08 at 10 46 20 AM" src="https://user-images.githubusercontent.com/5743014/183313902-ec94d52c-42c4-4cea-bc97-2f9abe2078b4.png">

**Comment by walterxie** [comment]
After the investigation, I realise it needs to use the [strictly version declaration](https://docs.gradle.org/current/userguide/rich_versions.html#sec:strict-version), so simply adding two "!" will solve this problem. When using the previous declaration (no !), the default behaviour is picking up any available highest version first, so that 1.3.0 was used instead of 1.2.0. 

`api("io.github.linguaphylo:lphy:1.2.0!!")`

 In addition, it should use `api` in phylonco-lphy build, and delete `implementation("io.github.linguaphylo:lphy:1.2.0")` from phylonco-lphybeast build, because `api` will pass it to  phylonco-lphybeast by using `implementation(project(":phylonco-lphy"))`.
 
 I do not think it is a bug, just the usage of Gradle dependencies. @kche309 I suggest to keep it is, but I will add the comments in lphy1.3 branch. If anyone wants the old version, they can change this in their local machine.
