### ISSUE TITLE
GT16ErrorModel doesn't have the narrative annotations

### ISSUE THREAD

**Issue by walterxie** [bioDS/beast-phylonco#32]
it looks like GT16ErrorModel doesn't have the narrative annotations, so its description in natural language is not very informative.

A simple example is 
https://github.com/LinguaPhylo/linguaPhylo/blob/d9c49b28aa996c4ed08074f92c2ef439f8e8533f/lphy/src/main/java/lphy/evolution/substitutionmodel/HKY.java#L39

**Comment by kche309** [comment]
I have done some debugging on this issue. The narrative annotations are in the code, but not shown on the narrative passage.

After some debugging, it appears an extra empty constructor was suppressing parameters from showing up in the GUI narrative description.

**Comment by kche309** [comment]
This is fixed in https://github.com/bioDS/beast-phylonco/pull/33/commits/d595522df1ce211433717afbe5d82e90e7d766a5

Testing with gt16CoalErrModel.lphy from examples in LPhyStudio produces:
![lphystudio-gt16-errormodel-narrative-fix](https://user-images.githubusercontent.com/8745224/185812419-33c53965-2630-4e36-8168-0dfac8d575f9.png)
